name: frontend
description: Explore the wonders of the universe with Lunar Glimpse
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  astro_common:
    path: ../common
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.0
  drift: ^2.18.0
  file_saver: ^0.2.12
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^14.1.0
  intl: ^0.18.1
  json_annotation: ^4.9.0
  logger: ^2.2.0
  lottie: ^3.1.0
  material_color_utilities: ^0.8.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.3
  rxdart: ^0.27.7
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  skeletonizer: ^1.1.2+1
  sqlite3: ^2.4.2
  sqlite3_flutter_libs: ^0.5.21
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.9
  drift_dev: ^2.18.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/animations/
    - assets/flags/
    - assets/app_logos/
