version: '3.9'

services:

  backend:
    image: ghcr.io/ilia-korolev/astro-backend:latest
    container_name: astro-backend-container
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_HOST: database
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    expose:
      - 5432
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}