name: flutter_astronomy
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.3.0
  collection: ^1.17.2
  dio: ^5.3.3
  drift: ^2.12.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^11.1.4
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  lottie: ^2.6.0
  material_color_utilities: ^0.5.0
  package_info_plus: ^4.2.0
  path: ^1.8.3
  path_provider: ^2.1.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sqlite3_flutter_libs: ^0.5.17

dev_dependencies:
  build_runner: ^2.4.6
  drift_dev: ^2.12.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  very_good_analysis: ^5.1.0

flutter:
  generate: true

  assets:
    - assets/animations/
