name: flutter_astronomy
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.3.0
  collection: ^1.18.0
  dio: ^5.4.0
  drift: ^2.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^12.1.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  lottie: ^2.7.0
  material_color_utilities: ^0.5.0
  package_info_plus: ^5.0.1
  path: ^1.8.3
  path_provider: ^2.1.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sqlite3_flutter_libs: ^0.5.18
  url_launcher: ^6.2.1
  xml: ^6.5.0

dev_dependencies:
  build_runner: ^2.4.7
  drift_dev: ^2.14.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  very_good_analysis: ^5.1.0

flutter:
  generate: true

  assets:
    - assets/animations/
