name: astro_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  astro_common:
    path: ../common
  dart_frog: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  postgres: ^3.1.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
