name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to file a bug report. Please provide us with detailed information to help us understand and address the issue."
  
  - type: input
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: "Ex: The gallery fails to load images..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: input
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: "Ex: Images should load smoothly without any error..."
    validations:
      required: true
  - type: dropdown
    id: device-information
    attributes:
      label: Device Information
      description: Please select the device where you encountered the bug.
      options:
        - Smartphone
        - Tablet
        - Desktop
        - Other
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: The operating system and version you are using.
      placeholder: "Ex: iOS 17, Windows 11..."
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      description: If applicable, the browser where the bug occurred.
      placeholder: "Ex: Chrome, Safari..."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: "Ex: The issue occurs only when I do..."
    validations:
      required: false
      