name: astro_common
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  dio: ^5.4.1
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  test: ^1.25.2
  very_good_analysis: ^5.1.0
